#!/bin/bash

# parameters - service username password
# GPG encryption

# IF THE GPG KEY WAS MISWRITTEN DELETE THE .bashpass/key FILE AND RERUN THE SCRIPT

trap 'enc;exit' 0 1 2 3 15 19
dbdir="$HOME/.bashpass"
db="$dbdir/db"
dbenc="$dbdir/db.gpg"
EDITOR=subl

enc() {
	# ENCRYPT
	gpg -e --trust-model always -r "$catkey" "$db"
	rm "$db"
}

dec() {
	# DECRYPT
	gpg -o "$db" -d "$dbenc"
	rm "$dbenc"
}


add() {
	[ ! -f "$dbenc" ] && enc
	service=$(printf "" | dmenu -p "Service:")
	case $service in
	"")
	notify-send "Error: invalid service" "Click to dismiss."
	exit 1
	;;
	esac
	dec
	if grep -wq "$service" "$db"
	then
		notify-send "Error: Service name used" "Click to dismiss."
		exit 1
	fi
	enc
	username=$(printf "" | dmenu -p "Username:")
	case $username in
	"")
	notify-send "Error: invalid username" "Click to dismiss."
	exit 1
	;;
	esac

	pass=$(printf "" | dmenu -p "Password:")
	case $pass in
	"")
	notify-send "Error: invalid password" "Click to dismiss."
	exit 1
	;;
	esac

	dec

	printf '%s %s %s\n' "$service" "$username" "$pass" >> "$db"


}

rem() {
	dec
	rmtrg=$(cat "$db" | awk '{print $1}' | sort | dmenu -i -p "Remove:")
	[ ! -z "$rmtrg" ] && grep -v "$rmtrg" $db > "${db}2"; mv "${db}2" "$db"
}


get() {
	dec
	servtrg=$(cat "$db" | awk '{print $1}' | sort | dmenu -i -p "Bashpass")
	if [ ! -z "$servtrg" ]; then
		uspassmenu=$(printf "Username\nPassword" | dmenu -i -p "Bashpass")
		case $uspassmenu in
		"Username")
		grep -w "$servtrg" "$db" | awk '{print $2}' | xclip -selection clipboard
		notify-send "💻 $servtrg's username copied to the clipboard." "Click to dismiss."

		;;
		"Password")
		grep -w "$servtrg" "$db" | awk '{print $3}' | xclip -selection clipboard
		notify-send "💻 $servtrg's password copied to the clipboard." "Click to dismiss."

		;;
		*)

		;;
		esac
	fi
}


[ ! -d "$dbdir"  ] && mkdir "$dbdir"

key="$dbdir/.key"

if [[ ! -f "$key" ]] || [ ! -s "$key" ]
then
	gpgmenu=$(printf "" | dmenu -p "GPG key:")

	case $gpgmenu in
	"")
	notify-send "Error: invalid GPG key" "Click to dismiss."
	exit 1
	;;
	esac

	printf "$gpgmenu" > "$key"

fi

catkey=`cat $key`

[[ -f "$db" && ! -f "$dbenc" ]] && enc

menu=$(printf "Add\nRemove\nGet" | dmenu -i -p "Bashpass")

case $menu in
"Add")
add ;;
"Get")
get ;;
"Remove")
rem ;;
*)
exit 1
;;
esac
